version: "3.9"

services:
  postgresql:
    image: postgres:13.4-alpine  # Latest version supported by RDS
    container_name: pg-events-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=events_api
    volumes:
      - ./resources/data:/var/log/postgresql/data:delegated
