version: "3.9"

services:
  postgresql:
    image: postgres:12.9-alpine  # Version in the cluster
    container_name: pg-events-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=events_api
    volumes:
      - ./resources/data:/var/log/postgresql/data:delegated
