apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "events-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/events/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/events/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/events/db/pass
      name: DB_PASSWORD
    - key: {{ .Release.Namespace }}/events/redis/host
      name: REDIS_HOST
    - key: {{ .Release.Namespace }}/events/redis/url
      name: REDIS_URL
    - key: {{ .Release.Namespace }}/events/redis/password
      name: REDIS_PASSWORD
    - key: {{ .Release.Namespace }}/events/smartcar/client_id
      name: SMARTCAR_CLIENT_ID
    - key: {{ .Release.Namespace }}/events/smartcar/client_secret
      name: SMARTCAR_CLIENT_SECRET
    - key: {{ .Release.Namespace }}/events/smartcar/webhook_id
      name: SMARTCAR_WEBHOOK_ID
